### ISSUE TITLE
I Know It’s Something Stupid I’m Not Doing

### ISSUE THREAD

**Issue by JChapman2** [xFrieDSpuDx/SMS-Bulk-Sender#4]
When I insert my key, I am not getting a balance, and messages aren’t sending. But everything else is functional. I have double-checked my key, number, and everything else. What am I missing? Any help is greatly appreciated. I uploaded a test at message.politicalcontenders.com so you can see functionality of the project. TIA

**Comment by xFrieDSpuDx** [comment]
I've taken a look, and I had a typo in the code. 
Thank you for pointing out a bug in the code.I have removed an unnecessary closing bracket.

One thing I noticed on your site is your errorHandler.js is a duplicate of post.js instead of the correct file.
If you try pulling down the latest version you should have success.

Kind regards

**Comment by JChapman2** [comment]
Thank you so much!!! That was it, works like a charm now. I knew it was something stupid I was doing wrong.  Thanks again!
